logger_level: 3
template_config: #单文件输出模板
   - name: 组件index模板
     file: template/组件index模板.ejs
   - name: 组件源代码模板
     file: template/组件源代码模板.ejs
   - name: 组件基础demo模板
     file: template/组件基础demo模板.ejs
   - name: 组件README模板
     file: template/组件README模板.ejs
   - name: 组件intro模板
     file: template/组件intro模板.ejs
   - name: 组件props模板
     file: template/组件props模板.ejs
   - name: 组件emits模板
     file: template/组件emits模板.ejs
   - name: 组件slots模板
     file: template/组件slots模板.ejs
   - name: 组件路由模板
     file: template/组件路由模板.ejs
   - name: 组件统一导出模板
     file: template/组件统一导出模板.ejs
file_config: # 单文件输出配置
   element: #element文件自动配置
      output_dir: /samples/components
      generator: # 代码生成器，使用相同参数，根据列表生成多个文件
         # ${默认大小写} $U{}全部大写 $L{}全部小写 $F{}首字母大写(仅转换首字母)
         - file: index.a.ts # 入口文件
           template: 组件index模板
           sub_dir: ${file_path}/${name} # 可根据参数替换
         - file: ${name}.vue # 源代码文件，可根据参数替换，
           template: 组件源代码模板
           overwrite: false
           sub_dir: ${file_path}/${name}/src
         - file: README.a.md # 演示文档
           template: 组件README模板
           sub_dir: ${file_path}/${name}/docs
         - file: intro.a.vue # 组件介绍
           template: 组件intro模板
           sub_dir: ${file_path}/${name}/docs
         - file: props.a.vue # 组件参数
           template: 组件props模板
           sub_dir: ${file_path}/${name}/docs
         - file: emits.a.vue # 组件事件
           template: 组件emits模板
           sub_dir: ${file_path}/${name}/docs
         - file: slots.a.vue # 组件插槽
           template: 组件slots模板
           sub_dir: ${file_path}/${name}/docs
         - file: demo1.vue # 默认演示文件
           spec: $.params.demos[0] # 指定属性，没有则不处理，如有，则替换成指定对象，可通过tempData.spec调用
           template: 组件基础demo模板
           sub_dir: ${file_path}/${name}/docs
         - file: demo2.vue # 演示文件2
           spec: $.params.demos[1] # 指定属性，没有则不处理，如有，则替换成指定对象，可通过tempData.spec调用
           template: 组件基础demo模板
           sub_dir: ${file_path}/${name}/docs
      group_generator: # list分组代码生成器，将多个文件的配置信息，统一在一个文件内输出模板
         - file: list.json # 路由文件
           filter_by: # 过滤条件，根据list项目里的某个属性进行过滤，支持JSON路径(需$.开头)
              "$.sub_dir": "${file_path}/${name}"
              "$.target_file": index.a.ts
          #  group_by: # 分组字段，根据list项目里的某个属性进行分组，支持JSON路径(需$.开头)，结果存入groupName
           template: 组件路由模板
         - file: index.a.ts # 路由文件
           filter_by: # 过滤字段，根据list项目里的某个属性进行过滤，支持JSON路径(需$.开头)
              "$.sub_dir": "${file_path}/${name}"
              "$.target_file": index.a.ts
           template: 组件统一导出模板
      list: # 多项目配置出来
         - name: Badge # 组件名称
           params: # 数据参数
              file_path: basic
              title: 徽标组件
              demos: 
                - title: 基础用法
                  code: |
                     <Button icon="pen">按钮</Button>
         - name: Button # 按钮组件
           params: # 数据参数
              file_path: basic
              title: 按钮组件
              demos: 
                - title: 基础用法
                  code: |
                     <Button icon="pen">按钮</Button>
         - name: Icon # 图标组件
           params: # 数据参数
              file_path: basic
              title: 图标组件
              demos:
                - title: 基础用法
                  code: |
                     <Icon icon="pen" />
                - title: 多图标自动切换
                  code: |
                     <Icon autoSwitch :icons="['pen', '']" />
         - name: Tooltip # 提示组件
           params: # 数据参数
              file_path: basic
              title: 提示组件
              demos:
                - title: 基础用法
                  code: |
                     <Tooltip content='按钮提示'>按钮</Tooltip>

